server:
  servlet:
    context-path: /api
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:./h2/form;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
logging:
  file:
    path: ./logs
